name: Pull Request Check

on:
  pull_request:
    paths:
      - "extension/**"
      - ".github/workflows/extension-pr.yml"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./extension

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "./extension/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Build extension
        run: npm run compile

      - name: Run tests
        run: npm test

      - name: Run tests with coverage
        run: npm run test:coverage 